version: "3.9"
services:
#  mqtt:
#    image: eclipse-mosquitto
#    container_name: mqtt
#    volumes:
#      - ./mosquitto:/mosquitto
#      - ./mosquitto/data:/mosquitto/data
#      - ./mosquitto/log:/mosquitto/log
#    ports:
#      - 1883:1883
#      - 9001:9001
#    networks:
#      mqtt_network:


  postgres_db:
    image: postgres:latest
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: test_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db/structure.sql:/docker-entrypoint-initdb.d/structure.sql
    ports:
      - "5432:5432"
    networks:
      db_network:


  store:
    container_name: store
    build: ../../store
    depends_on:
      - postgres_db
    restart: always
    environment:
      Store__PostgresConnectionString: "Server=postgres_db;Port=5432;Database=StoreDb;User Id=user;Password=pass;"
    ports:
      - "8000:80"
    networks:
      db_network:
      hub_store:


  hub:
    container_name: hub
    build: ../
    depends_on:
      #- mqtt
      - store
    environment:
      Hub__StoreBulkAddUrl: "http://store:80/api/processed-agent-data/bulk"
    ports:
      - "9000:80"
    networks:
      hub_store:


networks:
  #mqtt_network:
  db_network:
  hub_store:


volumes:
  postgres_data: