version: "3.9"
services:
  postgres_db:
    image: postgres:latest
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      db_network:


  store:
    container_name: store
    build: ..
    depends_on:
      - postgres_db
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: storeDb
      POSTGRES_HOST: localhost
      POSTGRES_PORT: 5432
    ports:
      - "8000:8000"
    networks:
      db_network:


networks:
  db_network:


volumes:
  postgres_data:
  pgadmin-data: